
export const APP_FEATURES = [
  {
    id : "01",
    title : "Tailored Just for You",
    description : "Get interview question and model answer based on your role, exprience and specific focus ares."
  },
  {
    id : "02",
    title : "Learn at Your own Place",
    description : "Expand answer only when you are ready. Dive deeper into any concept instantly with Ai powered explanations."
  },
  {
    id : "03",
    title : "Compute Your Insights",
    description : "Add personal notes to any question and pin importance ones to the top- making your Learning truly your own."
  },
  {
    id : "04",
    title :"Understand the 'why' Behind Answers",
    description : "Beyond just answers - unlock details concept explation generated by AI, helping you understand the 'why' and 'how' behind every solution."
  },
  {
    id: "05",
    title : "Save , Orgabize, and Revisit",
    description : "Easily save your interview sets, organize them neatly in your dashbpard, and pick up your prep right where you left off, anytime you want."

  }
]