export const CARD_BG = [
  {
    id: 1,
    bgcolor: "linear-gradient(135deg, #cfeee3 0%, #e9f7f1 100%)",
  },
  {
    id: 2,
    bgcolor: "linear-gradient(135deg, #f7edbf 0%, #fcf6dc 100%)",
  },
  {
    id: 3,
    bgcolor: "linear-gradient(135deg, #d2ebfa 0%, #e7f6fd 100%)",
  },
  {
    id: 4,
    bgcolor: "linear-gradient(135deg, #f7dcc8 0%, #fcecdf 100%)",
  },
  {
    id: 5,
    bgcolor: "linear-gradient(135deg, #d3eefc 0%, #e8f6fb 100%)",
  },
  {
    id: 6,
    bgcolor: "linear-gradient(135deg, #e0e0e0 0%, #f0f0f0 100%)",
  },
  {
    id: 7,
    bgcolor: "linear-gradient(135deg, #f9dcef 0%, #fdeef7 100%)",
  },
  {
    id: 8,
    bgcolor: "linear-gradient(135deg, #d1f7e3 0%, #e9fbf1 100%)",
  },
  {
    id: 9,
    bgcolor: "linear-gradient(135deg, #ddd5ff 0%, #eee9ff 100%)",
  },
  {
    id: 10,
    bgcolor: "linear-gradient(135deg, #f8d7d7 0%, #fceaea 100%)",
  },
];




export const APP_FEATURES = [
  {
    id : "01",
    title : "Tailored Just for You",
    description : "Get interview question and model answer based on your role, exprience and specific focus ares."
  },
  {
    id : "02",
    title : "Learn at Your own Place",
    description : "Expand answer only when you are ready. Dive deeper into any concept instantly with Ai powered explanations."
  },
  {
    id : "03",
    title : "Compute Your Insights",
    description : "Add personal notes to any question and pin importance ones to the top- making your Learning truly your own."
  },
  {
    id : "04",
    title :"Understand the 'why' Behind Answers",
    description : "Beyond just answers - unlock details concept explation generated by AI, helping you understand the 'why' and 'how' behind every solution."
  },
  {
    id: "05",
    title : "Save , Orgabize, and Revisit",
    description : "Easily save your interview sets, organize them neatly in your dashbpard, and pick up your prep right where you left off, anytime you want."

  }
]