export const CARD_BG = [
  {
    id: 1,
    bgcolor: "linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)",
  },
  {
    id: 2,
    bgcolor: "linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)",
  },
  {
    id: 3,
    bgcolor: "linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)",
  },
  {
    id: 4,
    bgcolor: "linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)",
  },
  {
    id: 5,
    bgcolor: "linear-gradient(135deg, #e7f6fe 0%, #f4fafd 100%)",
  },
  {
    id: 6,
    bgcolor: "linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)",
  },
  {
    id: 7,
    bgcolor: "linear-gradient(135deg, #fff4fc 0%, #fff8fd 100%)",
  },
  {
    id: 8,
    bgcolor: "linear-gradient(135deg, #e8fef3 0%, #f5fef8 100%)",
  },
  {
    id: 9,
    bgcolor: "linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)",
  },
  {
    id: 10,
    bgcolor: "linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)",
  },
];




export const APP_FEATURES = [
  {
    id : "01",
    title : "Tailored Just for You",
    description : "Get interview question and model answer based on your role, exprience and specific focus ares."
  },
  {
    id : "02",
    title : "Learn at Your own Place",
    description : "Expand answer only when you are ready. Dive deeper into any concept instantly with Ai powered explanations."
  },
  {
    id : "03",
    title : "Compute Your Insights",
    description : "Add personal notes to any question and pin importance ones to the top- making your Learning truly your own."
  },
  {
    id : "04",
    title :"Understand the 'why' Behind Answers",
    description : "Beyond just answers - unlock details concept explation generated by AI, helping you understand the 'why' and 'how' behind every solution."
  },
  {
    id: "05",
    title : "Save , Orgabize, and Revisit",
    description : "Easily save your interview sets, organize them neatly in your dashbpard, and pick up your prep right where you left off, anytime you want."

  }
]